apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.40.0

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 5000

  - name: Lux Node
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9650/ext/metrics
    editable: true
    jsonData:
      httpMethod: GET

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: lux-postgres:5432
    database: explorer_luxnet
    user: blockscout
    secureJsonData:
      password: blockscout
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false